title: "Betelgeuse"
working-title: "Betelgeuse"
email: 

permalink:  /:categories/:title/
description: > 
  A Theme for which I have high hopes
baseurl: "" 
url: "http://nup.pii.at"

markdown: kramdown

source: _source
destination: _build

sass:
  sass_dir: _sass
  style: compressed

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']